# Use root as user credentials
version: '3.1'

services:

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: karin111
      # MYSQL_USER: root
    ports:
      - 3307:3306
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_bin",
      ]

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  default:
    name: mysql
